# Default values for compair.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
stage: dev
dbPort: "3306"
dbName: compair
dbUsername: compair
dbPassword: PLEASE_CHANGE_ME
celeryBrokerURL: redis://{{ template "fullname" . }}-redis:6379
assetLocation: local
enforceSSL: true
cForceRoot: true
attachmentUploadLimit: "262144000" #1024 * 1024 * 250 -> max 250MB
secretKey: LRS_RANDOM_KEY
workerSchedulerEnabled: false
demoInstance: false
celeryTimezone: America/Vancouver
appLoginEnabled: true
ltiLoginEnabled: false

# cas settings
cas:
  enabled: false
  server: https://cas.example.com
  authPrefix: /cas
  useSAML: false
  attributeFirstName: firstName
  attributeLastName: lastName
  attributeStudentNumber: studentNumber
  attributeEmail: mail

# email notifications settings
mail:
  enabled: false
  server: https://mail.example.com
  port: "1025"
  useSSL: true
  useTLS: false
  username: compair
  password: PLEASE_CHANGE_ME
  defaultSender: compair@example.com

# kaltura media attachments settings
kaltura:
  enabled: false
  serviceURL: https://kaltura.example.com
  partnerId: "1234"
  secret: PLEASE_CHANGE_ME
  userId: "1234"
  playerId: "1234"

# xapi settings
xapi:
  enabled: false
  appBaseURL: https://archive.org/services/purl/compair/ctlt/
  lrsStatementEndpoint: https://lrs.example.com/data/xAPI/
  lrsActorAccountUseCas: false
  lrsActorAccountCasIdentifier: uid
  lrsActorAccountCasHomepage: http://www.example.com/
  lrsUsername: lrs
  lrsPassword: LRS_PASSWORD

# data privacy settings
expose:
  emailToInstructor: false
  casUsernameToInstructor: false

# profile editing controls
allowStudentChange:
  name: 1
  displayName: 1
  studentNumber: 1
  email: 1

app:
  replicaCount: 1
  image:
    repository: ubcctlt/compair-app
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    # auto provision
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 10Gi
    # NFS
    #accessMode: ReadWriteMany
    #resources:
    #  nfs:
    #    server: NSF_SERVER_IP
    #    path: "/export/data/compair"
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 3031
  ingress:
    enabled: true
    class: nginx
    #host: compair.example.com

worker:
  replicaCount: 1
  image:
    repository: ubcctlt/compair-app
    tag: latest
    pullPolicy: IfNotPresent

db:
  image:
    repository: mariadb
    tag: 10.1
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 8Gi

redis:
  image:
    repository: redis
    tag: 3.2.4
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: false
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 1Gi
